In [1]:
import pandas as pd
import numpy as np

In [2]:
# CREATING SERIES
l = [11,22,33,44,55]
arr = np.array([1,2,3,4,5])
d = {1:10,2:20,3:30,4:40,5:50}
labels = ["A","B","C","D","E"]

In [3]:
pd.Series(l,index=labels)

A    11
B    22
C    33
D    44
E    55
dtype: int64

In [4]:
pd.Series(d)

1    10
2    20
3    30
4    40
5    50
dtype: int64

In [5]:
# CREATING DATAFRAME

In [6]:
# CREATING DATAFRAME USING DICTIONARY
data = {
    "Name" : ["Johan","Anna","Piter","Linda"],
    "Age" : [19,24,25,28],
    "City" : ["New York","Paris","Berlin","London"],
    "Salary":[50000,65000,45000,38000]
}
d = pd.DataFrame(data)
print(d)

    Name  Age      City  Salary
0  Johan   19  New York   50000
1   Anna   24     Paris   65000
2  Piter   25    Berlin   45000
3  Linda   28    London   38000

In [7]:
# CREATING DATAFRAME USING LIST
list =[ ["Johan","Anna","Piter","Linda"],
        [19,24,25,28],
        ["New York","Paris","Berlin","London"],
        [50000,65000,45000,38000] ]
c = ["Name","Age","City","Salary"]
d2 = pd.DataFrame(list,columns=c)
print(d2)

       Name    Age    City  Salary
0     Johan   Anna   Piter   Linda
1        19     24      25      28
2  New York  Paris  Berlin  London
3     50000  65000   45000   38000

In [8]:


# SELECTION AND INDEXING OF COLUMNS

In [9]:
d["Age"]

0    19
1    24
2    25
3    28
Name: Age, dtype: int64

In [10]:
d[["Name","Salary"]]

    Name  Salary
0  Johan   50000
1   Anna   65000
2  Piter   45000
3  Linda   38000

In [11]:
d['Name']

0    Johan
1     Anna
2    Piter
3    Linda
Name: Name, dtype: object

In [12]:
# CREATING NEW COLUMNS
d["Department"] = ["D01","D03","D02","D04"]
print(d)

    Name  Age      City  Salary Department
0  Johan   19  New York   50000        D01
1   Anna   24     Paris   65000        D03
2  Piter   25    Berlin   45000        D02
3  Linda   28    London   38000        D04

In [13]:
# REMOVING COLUMNS

In [14]:
# TEMPORARY REMOVING COLUMNS
d.drop('Department', axis = 1)

    Name  Age      City  Salary
0  Johan   19  New York   50000
1   Anna   24     Paris   65000
2  Piter   25    Berlin   45000
3  Linda   28    London   38000

In [15]:
print(d)

    Name  Age      City  Salary Department
0  Johan   19  New York   50000        D01
1   Anna   24     Paris   65000        D03
2  Piter   25    Berlin   45000        D02
3  Linda   28    London   38000        D04

In [16]:
# PARMANENTE REMOVING COLUMNS
d.drop("Department",axis=1,inplace=True)
print(d)

    Name  Age      City  Salary
0  Johan   19  New York   50000
1   Anna   24     Paris   65000
2  Piter   25    Berlin   45000
3  Linda   28    London   38000

In [17]:
d.drop(["Age","City"], axis = 1)

    Name  Salary
0  Johan   50000
1   Anna   65000
2  Piter   45000
3  Linda   38000

In [18]:
print(d)

    Name  Age      City  Salary
0  Johan   19  New York   50000
1   Anna   24     Paris   65000
2  Piter   25    Berlin   45000
3  Linda   28    London   38000

In [19]:
# REMOVING A ROW

In [20]:
d.drop(0,axis = 0)

    Name  Age    City  Salary
1   Anna   24   Paris   65000
2  Piter   25  Berlin   45000
3  Linda   28  London   38000

In [21]:
#SELECTING ROWS

In [22]:
print(d)

    Name  Age      City  Salary
0  Johan   19  New York   50000
1   Anna   24     Paris   65000
2  Piter   25    Berlin   45000
3  Linda   28    London   38000

In [23]:
print(d.loc[0])

Name         Johan
Age             19
City      New York
Salary       50000
Name: 0, dtype: object

In [24]:
print(d.loc[[1,2]])

    Name  Age    City  Salary
1   Anna   24   Paris   65000
2  Piter   25  Berlin   45000

In [25]:
print(d.iloc[3])

Name       Linda
Age           28
City      London
Salary     38000
Name: 3, dtype: object

In [26]:
#SELECTING SUBSET OF ROWS AND COLUMNS

In [27]:
print(d)

    Name  Age      City  Salary
0  Johan   19  New York   50000
1   Anna   24     Paris   65000
2  Piter   25    Berlin   45000
3  Linda   28    London   38000

In [28]:
print(d.loc[[0,1]] [["Name","Salary"]])

    Name  Salary
0  Johan   50000
1   Anna   65000

In [29]:
print(d.loc[[2,3]] [["Name","Age"]])

    Name  Age
2  Piter   25
3  Linda   28

In [30]:
#  CONDETION SELECTION

In [31]:
print(d)

    Name  Age      City  Salary
0  Johan   19  New York   50000
1   Anna   24     Paris   65000
2  Piter   25    Berlin   45000
3  Linda   28    London   38000

In [32]:
d[d["Age"]>=25]

    Name  Age    City  Salary
2  Piter   25  Berlin   45000
3  Linda   28  London   38000

In [33]:
d[ (d["Salary"] > 40000) & (d["Age"] > 20)]

    Name  Age    City  Salary
1   Anna   24   Paris   65000
2  Piter   25  Berlin   45000

In [34]:
d[d["Salary"]>50000] ["Name"]

1    Anna
Name: Name, dtype: object

In [35]:
# MISSING DATA HANDLING

In [36]:
data2 = {
    'A': [1,2,np.nan,4,5],
    'B': [np.nan,2,3,4,5],
    'C': [1,2,3,np.nan,np.nan],
    'D': [1,np.nan,np.nan,np.nan,5],
    'E': [1,2,3,4,5]
}

In [37]:
df = pd.DataFrame(data2)
print(df)

     A    B    C    D  E
0  1.0  NaN  1.0  1.0  1
1  2.0  2.0  2.0  NaN  2
2  NaN  3.0  3.0  NaN  3
3  4.0  4.0  NaN  NaN  4
4  5.0  5.0  NaN  5.0  5

In [38]:
#FINDING MISSING DATA

In [39]:
df.isna()

       A      B      C      D      E
0  False   True  False  False  False
1  False  False  False   True  False
2   True  False  False   True  False
3  False  False   True   True  False
4  False  False   True  False  False

In [40]:
df.isnull()

       A      B      C      D      E
0  False   True  False  False  False
1  False  False  False   True  False
2   True  False  False   True  False
3  False  False   True   True  False
4  False  False   True  False  False

In [41]:
df.isnull().sum()

A    1
B    1
C    2
D    3
E    0
dtype: int64

In [42]:
df.isnull().any()

A     True
B     True
C     True
D     True
E    False
dtype: bool

In [43]:
# REMOVING MISSING DATA

In [44]:
print(df)

     A    B    C    D  E
0  1.0  NaN  1.0  1.0  1
1  2.0  2.0  2.0  NaN  2
2  NaN  3.0  3.0  NaN  3
3  4.0  4.0  NaN  NaN  4
4  5.0  5.0  NaN  5.0  5

In [45]:
print(df.dropna(axis=1))

   E
0  1
1  2
2  3
3  4
4  5

In [46]:
print(df.dropna(thresh=4))

     A    B    C    D  E
0  1.0  NaN  1.0  1.0  1
1  2.0  2.0  2.0  NaN  2
4  5.0  5.0  NaN  5.0  5

In [47]:
# FILLING MISSING DATA

In [48]:
print(df)

     A    B    C    D  E
0  1.0  NaN  1.0  1.0  1
1  2.0  2.0  2.0  NaN  2
2  NaN  3.0  3.0  NaN  3
3  4.0  4.0  NaN  NaN  4
4  5.0  5.0  NaN  5.0  5

In [49]:
print(df.fillna('k'))

     A    B    C    D  E
0  1.0    k  1.0  1.0  1
1  2.0  2.0  2.0    k  2
2    k  3.0  3.0    k  3
3  4.0  4.0    k    k  4
4  5.0  5.0    k  5.0  5

In [50]:
v = {
    'A' :100,
    'B': 200,
    'C': 300,
    'D': 400,
    "E": 500
}

In [51]:
print(df.fillna(v))

       A      B      C      D  E
0    1.0  200.0    1.0    1.0  1
1    2.0    2.0    2.0  400.0  2
2  100.0    3.0    3.0  400.0  3
3    4.0    4.0  300.0  400.0  4
4    5.0    5.0  300.0    5.0  5

In [52]:
print(df.fillna(df.mean()))

     A    B    C    D  E
0  1.0  3.5  1.0  1.0  1
1  2.0  2.0  2.0  3.0  2
2  3.0  3.0  3.0  3.0  3
3  4.0  4.0  2.0  3.0  4
4  5.0  5.0  2.0  5.0  5

In [53]:
# MERGING DATAFRAMES

In [54]:
employee = {
    'employee_id':[1,2,3,4,5],
    'name':['johan','anna','piter','linda','bob'],
    'department':['HR','IT','Finance','Marketing','Sales']
}
Salary = {
    'employee_id':[1,2,3,6,7],
    'salary':[50000,66000,55000,72000,50000],
    'bomus':[5000,7000,8000,45000,6000]
}

In [55]:
employee=pd.DataFrame(employee)
print(employee)

   employee_id   name department
0            1  johan         HR
1            2   anna         IT
2            3  piter    Finance
3            4  linda  Marketing
4            5    bob      Sales

In [56]:
salary =pd.DataFrame(Salary)
print(salary)

   employee_id  salary  bomus
0            1   50000   5000
1            2   66000   7000
2            3   55000   8000
3            6   72000  45000
4            7   50000   6000

In [57]:
pd.merge(employee,salary,on='employee_id')

   employee_id   name department  salary  bomus
0            1  johan         HR   50000   5000
1            2   anna         IT   66000   7000
2            3  piter    Finance   55000   8000

In [58]:
pd.merge(employee,salary,on='employee_id',how='outer')

   employee_id   name department   salary    bomus
0            1  johan         HR  50000.0   5000.0
1            2   anna         IT  66000.0   7000.0
2            3  piter    Finance  55000.0   8000.0
3            4  linda  Marketing      NaN      NaN
4            5    bob      Sales      NaN      NaN
5            6    NaN        NaN  72000.0  45000.0
6            7    NaN        NaN  50000.0   6000.0

In [59]:
pd.merge(employee,salary, on = 'employee_id' , how = 'left')

   employee_id   name department   salary   bomus
0            1  johan         HR  50000.0  5000.0
1            2   anna         IT  66000.0  7000.0
2            3  piter    Finance  55000.0  8000.0
3            4  linda  Marketing      NaN     NaN
4            5    bob      Sales      NaN     NaN

In [60]:
pd.merge(employee,salary,on='employee_id',how='right')

   employee_id   name department  salary  bomus
0            1  johan         HR   50000   5000
1            2   anna         IT   66000   7000
2            3  piter    Finance   55000   8000
3            6    NaN        NaN   72000  45000
4            7    NaN        NaN   50000   6000

In [61]:
# CONCATENATING OF 2 DATAFRAMES

In [62]:
df1 = pd.DataFrame({
    'A':['A0',"A1","A2"],
    'B':['B0',"B1","B2"],
    'C':['C0',"C1","C2"]
})
df2 = pd.DataFrame({
    'A':['A3',"A4","A5"],
    'B':['B3',"B4","B5"],
    'C':['C3',"C4","C5"]
})

In [63]:
print(df1)
print(df2)

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2
    A   B   C
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [64]:
pd.concat([df1,df2])

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [65]:
pd.concat([df1,df2],axis=1)

    A   B   C   A   B   C
0  A0  B0  C0  A3  B3  C3
1  A1  B1  C1  A4  B4  C4
2  A2  B2  C2  A5  B5  C5

In [66]:

# JOINING OF 2 DATAFRAMES

In [67]:
data1 = pd.DataFrame({
    'name':['Alice','Bob','Charlie'],
},index = [1,2,3])
data2 =pd.DataFrame({
    'score':[85,90,95]
},index = [2,3,4])

In [68]:
print(data1)
print(data2)

      name
1    Alice
2      Bob
3  Charlie
   score
2     85
3     90
4     95

In [69]:
data1.join(data2)

      name  score
1    Alice    NaN
2      Bob   85.0
3  Charlie   90.0

In [70]:
data1.join(data2,how='outer')

      name  score
1    Alice    NaN
2      Bob   85.0
3  Charlie   90.0
4      NaN   95.0

In [71]:
data2.join(data1)

   score     name
2     85      Bob
3     90  Charlie
4     95      NaN

In [72]:
data2.join(data1,how='outer')

   score     name
1    NaN    Alice
2   85.0      Bob
3   90.0  Charlie
4   95.0      NaN

In [73]:
# GROUP_BY

In [74]:
data = pd.DataFrame({
    'category':['A','B','A','B','A','B','A','B'],
    'store':['S1','S1','S2','S2','S1','S2','S1','S2'],
    'sales':[100,200,150, 250,120,180,400,450],
    'quantity':[10,20,15,25,30,35,40,45],
    'date':pd.date_range(start='2026-01-01',periods=8)
})

In [75]:
print(data)

  category store  sales  quantity       date
0        A    S1    100        10 2026-01-01
1        B    S1    200        20 2026-01-02
2        A    S2    150        15 2026-01-03
3        B    S2    250        25 2026-01-04
4        A    S1    120        30 2026-01-05
5        B    S2    180        35 2026-01-06
6        A    S1    400        40 2026-01-07
7        B    S2    450        45 2026-01-08

In [76]:
# GROUP BY CATEGORY AND  CALUCLATE SUM OF SALES
data.groupby('category')['sales'].sum()

category
A     770
B    1080
Name: sales, dtype: int64

In [77]:
# GROUP BY STORE AND CALCULATE SALES
data.groupby('store')['sales'].sum()

store
S1     820
S2    1030
Name: sales, dtype: int64

In [78]:
# GROUP BY MULTIPLE COLUMNS
data.groupby(['category','store'])['sales'].sum()

category  store
A         S1       620
          S2       150
B         S1       200
          S2       880
Name: sales, dtype: int64

In [79]:
# AGGREGATION

In [80]:
print(data)

  category store  sales  quantity       date
0        A    S1    100        10 2026-01-01
1        B    S1    200        20 2026-01-02
2        A    S2    150        15 2026-01-03
3        B    S2    250        25 2026-01-04
4        A    S1    120        30 2026-01-05
5        B    S2    180        35 2026-01-06
6        A    S1    400        40 2026-01-07
7        B    S2    450        45 2026-01-08

In [81]:
data['sales'].max()

np.int64(450)

In [82]:
data["sales"].mean()

np.float64(231.25)

In [83]:
data['category'].value_counts()

category
A    4
B    4
Name: count, dtype: int64

In [84]:
data['sales'].min()

np.int64(100)

In [85]:
data['sales'].std()

np.float64(129.00027685463093)

In [86]:
data['sales'].median()

np.float64(190.0)

In [87]:
data["sales"].agg(['min',"max","mean","median"])

min       100.00
max       450.00
mean      231.25
median    190.00
Name: sales, dtype: float64

In [88]:
# PIVAT TABLE

In [89]:
d =pd.DataFrame({
    'date':pd.date_range(start='2023-01-01',periods=20),
    'product':['A','B','C','D']*5,
    'region':['east','west','north','south']*5,
    'sales':np.random.randint(100,1000,20),
    'units':np.random.randint(10,100,20),
    'rep':['John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary',
            'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice']
})
d["month"]=d['date'].dt.month_name()
d['quarter']='Q'+d['date'].dt.quarter.astype(str)
print(d)

         date product region  sales  units    rep    month quarter
0  2023-01-01       A   east    372     27   John  January      Q1
1  2023-01-02       B   west    954     43   Mary  January      Q1
2  2023-01-03       C  north    302     70    Bob  January      Q1
3  2023-01-04       D  south    352     33  Alice  January      Q1
4  2023-01-05       A   east    531     51   John  January      Q1
5  2023-01-06       B   west    682     92   Mary  January      Q1
6  2023-01-07       C  north    491     59    Bob  January      Q1
7  2023-01-08       D  south    625     24  Alice  January      Q1
8  2023-01-09       A   east    329     86   John  January      Q1
9  2023-01-10       B   west    542     28   Mary  January      Q1
10 2023-01-11       C  north    946     71    Bob  January      Q1
11 2023-01-12       D  south    458     10  Alice  January      Q1
12 2023-01-13       A   east    878     16   John  January      Q1
13 2023-01-14       B   west    336     64   Mary  January      Q1
14 2023-01-15       C  north    557     93    Bob  January      Q1
15 2023-01-16       D  south    207     30  Alice  January      Q1
16 2023-01-17       A   east    879     95   John  January      Q1
17 2023-01-18       B   west    786     30   Mary  January      Q1
18 2023-01-19       C  north    612     60    Bob  January      Q1
19 2023-01-20       D  south    951     88  Alice  January      Q1

In [90]:
pd.pivot_table(d, values='sales', index = 'region',columns='product')

product      A      B      C      D
region
east     597.8    NaN    NaN    NaN
north      NaN    NaN  581.6    NaN
south      NaN    NaN    NaN  518.6
west       NaN  660.0    NaN    NaN

In [91]:
pd.pivot_table(d,values =['sales','units'],index='region',columns="product")

         sales                      units
product      A      B      C      D     A     B     C     D
region
east     597.8    NaN    NaN    NaN  55.0   NaN   NaN   NaN
north      NaN    NaN  581.6    NaN   NaN   NaN  70.6   NaN
south      NaN    NaN    NaN  518.6   NaN   NaN   NaN  37.0
west       NaN  660.0    NaN    NaN   NaN  51.4   NaN   NaN

In [92]:
# CROSS TABS

In [93]:
pd.crosstab(d['region'],d['product'])

product  A  B  C  D
region
east     5  0  0  0
north    0  0  5  0
south    0  0  0  5
west     0  5  0  0

In [94]:
# DATAFAMES BASICS OPERATONS

In [95]:
df1 = pd.DataFrame({
    'A':[1,2,3,4,5],
    'B':[10,20,30,40,50],
    'C':[100,200,300,400,500]
})

In [96]:
print(df1)

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [97]:
df1.shape

(5, 3)

In [98]:
df1.columns

Index(['A', 'B', 'C'], dtype='object')

In [99]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       5 non-null      int64
 1   B       5 non-null      int64
 2   C       5 non-null      int64
dtypes: int64(3)
memory usage: 252.0 bytes

In [100]:
df1.describe()

              A          B           C
count  5.000000   5.000000    5.000000
mean   3.000000  30.000000  300.000000
std    1.581139  15.811388  158.113883
min    1.000000  10.000000  100.000000
25%    2.000000  20.000000  200.000000
50%    3.000000  30.000000  300.000000
75%    4.000000  40.000000  400.000000
max    5.000000  50.000000  500.000000

In [101]:
df1['A']+10

0    11
1    12
2    13
3    14
4    15
Name: A, dtype: int64

In [102]:
# DATAFRAME APPLYING  FUNCTIONS

In [103]:
print(df1)

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [104]:
def square(x):
    return x**2

In [105]:
df1['D'] =df1['B'].apply(square)
print(df1)

   A   B    C     D
0  1  10  100   100
1  2  20  200   400
2  3  30  300   900
3  4  40  400  1600
4  5  50  500  2500

In [109]:
# QUICK EXAMPLE OF READING A Anime CSV FILE
data3 = pd.read_csv(r'pandas_anime.csv')
print(data3)

    Rank                                              Title  Score
0      1  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10
1      2  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   9.07
2      3  Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...   9.06
3      4  Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...   9.06
4      5  Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...   9.05
5      6  Gintama'TV (51 eps)Apr 2011 - Mar 2012534,105 ...   9.04
6      7  Gintama: The FinalMovie (1 eps)Jan 2021 - Jan ...   9.04
7      8  Hunter x Hunter TV (148 eps)Oct 2011 - Sep 201...   9.04
8      9  Kaguya-sama wa Kokurasetai: Ultra RomanticTV (...   9.04
9     10  Gintama': EnchousenTV (13 eps)Oct 2012 - Mar 2...   9.03
10    11  Shingeki no Kyojin: The Final Season - Kankets...   9.03
11    12  Ginga Eiyuu DensetsuOVA (110 eps)Jan 1988 - Ma...   9.02
12    13  Bleach: Sennen Kessen-hen - Ketsubetsu-tanTV (...   8.99
13    14  Fruits Basket: The FinalTV (13 eps)Apr 2021 - ...   8.99
14    15  Gintama.TV (12 eps)Jan 2017 - Mar 2017302,232 ...   8.98
15    16  GintamaTV (201 eps)Apr 2006 - Mar 20101,034,41...   8.94
16    17  Koe no KatachiMovie (1 eps)Sep 2016 - Sep 2016...   8.94
17    18  3-gatsu no Lion 2nd SeasonTV (22 eps)Oct 2017 ...   8.93
18    19  Clannad: After StoryTV (24 eps)Oct 2008 - Mar ...   8.93
19    20  Code Geass: Hangyaku no Lelouch R2TV (25 eps)A...   8.91
20    21  Gintama Movie 2: Kanketsu-hen - Yorozuya yo Ei...   8.91
21    22  Violet Evergarden MovieMovie (1 eps)Sep 2020 -...   8.89
22    23  Owarimonogatari 2nd SeasonTV (7 eps)Aug 2017 -...   8.88
23    24  Gintama.: Shirogane no Tamashii-hen - Kouhan-s...   8.88
24    25  MonsterTV (74 eps)Apr 2004 - Sep 20051,041,081...   8.87
25    26  Kimi no Na wa.Movie (1 eps)Aug 2016 - Aug 2016...   8.84
26    27  Kaguya-sama wa Kokurasetai: First Kiss wa Owar...   8.84
27    28  Bocchi the Rock!TV (12 eps)Oct 2022 - Dec 2022...   8.83
28    29  The First Slam DunkMovie (1 eps)Dec 2022 - Dec...   8.83
29    30  Vinland Saga Season 2TV (24 eps)Jan 2023 - Jun...   8.82
30    31  Jujutsu Kaisen 2nd SeasonTV (23 eps)Jul 2023 -...   8.82
31    32  Gintama.: Shirogane no Tamashii-henTV (12 eps)...   8.81
32    33  Kingdom 3rd SeasonTV (26 eps)Apr 2020 - Oct 20...   8.81
33    34  Mob Psycho 100 IITV (13 eps)Jan 2019 - Apr 201...   8.80
34    35  Shingeki no Kyojin: The Final SeasonTV (16 eps...   8.80
35    36  Kimetsu no Yaiba: Yuukaku-henTV (11 eps)Dec 20...   8.79
36    37  Kizumonogatari III: Reiketsu-henMovie (1 eps)J...   8.79
37    38  "Oshi no Ko"TV (11 eps)Apr 2023 - Jun 2023645,...   8.79
38    39  Haikyuu!! Karasuno Koukou vs. Shiratorizawa Ga...   8.78
39    40  Sen to Chihiro no KamikakushiMovie (1 eps)Jul ...   8.78
40    41  Monogatari Series: Second SeasonTV (26 eps)Jul...   8.77
41    42  Shingeki no Kyojin: The Final Season Part 2TV ...   8.77
42    43  Hajime no IppoTV (75 eps)Oct 2000 - Mar 200255...   8.76
43    44  Cowboy BebopTV (26 eps)Apr 1998 - Apr 19991,79...   8.75
44    45  Kingdom 4th SeasonTV (26 eps)Apr 2022 - Oct 20...   8.75
45    46  Vinland SagaTV (24 eps)Jul 2019 - Dec 20191,40...   8.74
46    47  Mushishi Zoku Shou 2nd SeasonTV (10 eps)Oct 20...   8.73
47    48  Shouwa Genroku Rakugo Shinjuu: Sukeroku Futata...   8.72
48    49  Mob Psycho 100 IIITV (12 eps)Oct 2022 - Dec 20...   8.71
49    50  Rurouni Kenshin: Meiji Kenkaku Romantan - Tsui...   8.71

In [110]:
data3.head(8)

   Rank                                              Title  Score
0     1  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10
1     2  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   9.07
2     3  Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...   9.06
3     4  Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...   9.06
4     5  Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...   9.05
5     6  Gintama'TV (51 eps)Apr 2011 - Mar 2012534,105 ...   9.04
6     7  Gintama: The FinalMovie (1 eps)Jan 2021 - Jan ...   9.04
7     8  Hunter x Hunter TV (148 eps)Oct 2011 - Sep 201...   9.04

In [111]:
# make a new column for episode count
def episode_count(txt):
    episodes =''
    check = False
    for i in range(len(txt)):
        if txt[i] == ')':
            break
        if txt[i] == '(':
            check = True
            continue
        if check == True:
            episodes += txt[i]
    return episodes
data3['episode'] = data3['Title'].apply(episode_count)   
data3['episode'] = data3['episode'].str.replace("eps","")
data3['episode'] = data3['episode'].astype('int')

In [112]:
data3

    Rank                                              Title  Score  episode
0      1  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10       64
1      2  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   9.07       24
2      3  Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...   9.06       13
3      4  Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...   9.06       51
4      5  Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...   9.05       10
5      6  Gintama'TV (51 eps)Apr 2011 - Mar 2012534,105 ...   9.04       51
6      7  Gintama: The FinalMovie (1 eps)Jan 2021 - Jan ...   9.04        1
7      8  Hunter x Hunter TV (148 eps)Oct 2011 - Sep 201...   9.04      148
8      9  Kaguya-sama wa Kokurasetai: Ultra RomanticTV (...   9.04       13
9     10  Gintama': EnchousenTV (13 eps)Oct 2012 - Mar 2...   9.03       13
10    11  Shingeki no Kyojin: The Final Season - Kankets...   9.03        2
11    12  Ginga Eiyuu DensetsuOVA (110 eps)Jan 1988 - Ma...   9.02      110
12    13  Bleach: Sennen Kessen-hen - Ketsubetsu-tanTV (...   8.99       13
13    14  Fruits Basket: The FinalTV (13 eps)Apr 2021 - ...   8.99       13
14    15  Gintama.TV (12 eps)Jan 2017 - Mar 2017302,232 ...   8.98       12
15    16  GintamaTV (201 eps)Apr 2006 - Mar 20101,034,41...   8.94      201
16    17  Koe no KatachiMovie (1 eps)Sep 2016 - Sep 2016...   8.94        1
17    18  3-gatsu no Lion 2nd SeasonTV (22 eps)Oct 2017 ...   8.93       22
18    19  Clannad: After StoryTV (24 eps)Oct 2008 - Mar ...   8.93       24
19    20  Code Geass: Hangyaku no Lelouch R2TV (25 eps)A...   8.91       25
20    21  Gintama Movie 2: Kanketsu-hen - Yorozuya yo Ei...   8.91        1
21    22  Violet Evergarden MovieMovie (1 eps)Sep 2020 -...   8.89        1
22    23  Owarimonogatari 2nd SeasonTV (7 eps)Aug 2017 -...   8.88        7
23    24  Gintama.: Shirogane no Tamashii-hen - Kouhan-s...   8.88       14
24    25  MonsterTV (74 eps)Apr 2004 - Sep 20051,041,081...   8.87       74
25    26  Kimi no Na wa.Movie (1 eps)Aug 2016 - Aug 2016...   8.84        1
26    27  Kaguya-sama wa Kokurasetai: First Kiss wa Owar...   8.84        1
27    28  Bocchi the Rock!TV (12 eps)Oct 2022 - Dec 2022...   8.83       12
28    29  The First Slam DunkMovie (1 eps)Dec 2022 - Dec...   8.83        1
29    30  Vinland Saga Season 2TV (24 eps)Jan 2023 - Jun...   8.82       24
30    31  Jujutsu Kaisen 2nd SeasonTV (23 eps)Jul 2023 -...   8.82       23
31    32  Gintama.: Shirogane no Tamashii-henTV (12 eps)...   8.81       12
32    33  Kingdom 3rd SeasonTV (26 eps)Apr 2020 - Oct 20...   8.81       26
33    34  Mob Psycho 100 IITV (13 eps)Jan 2019 - Apr 201...   8.80       13
34    35  Shingeki no Kyojin: The Final SeasonTV (16 eps...   8.80       16
35    36  Kimetsu no Yaiba: Yuukaku-henTV (11 eps)Dec 20...   8.79       11
36    37  Kizumonogatari III: Reiketsu-henMovie (1 eps)J...   8.79        1
37    38  "Oshi no Ko"TV (11 eps)Apr 2023 - Jun 2023645,...   8.79       11
38    39  Haikyuu!! Karasuno Koukou vs. Shiratorizawa Ga...   8.78       10
39    40  Sen to Chihiro no KamikakushiMovie (1 eps)Jul ...   8.78        1
40    41  Monogatari Series: Second SeasonTV (26 eps)Jul...   8.77       26
41    42  Shingeki no Kyojin: The Final Season Part 2TV ...   8.77       12
42    43  Hajime no IppoTV (75 eps)Oct 2000 - Mar 200255...   8.76       75
43    44  Cowboy BebopTV (26 eps)Apr 1998 - Apr 19991,79...   8.75       26
44    45  Kingdom 4th SeasonTV (26 eps)Apr 2022 - Oct 20...   8.75       26
45    46  Vinland SagaTV (24 eps)Jul 2019 - Dec 20191,40...   8.74       24
46    47  Mushishi Zoku Shou 2nd SeasonTV (10 eps)Oct 20...   8.73       10
47    48  Shouwa Genroku Rakugo Shinjuu: Sukeroku Futata...   8.72       12
48    49  Mob Psycho 100 IIITV (12 eps)Oct 2022 - Dec 20...   8.71       12
49    50  Rurouni Kenshin: Meiji Kenkaku Romantan - Tsui...   8.71        4

In [246]:
# make a new column for time stamp
def time_stamp(txt):
    time =''
    check = False
    for i in range(len(txt)):
        if txt[i] == ')':
            for j in range(i+1,i+20):
                time += txt[j]
            break
    return time
data3['title_time'] = data3['Title'].apply(time_stamp)
data3

,Rank,Title,Score,episode,title_time
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.10,64,Apr 2009 - Jul 2010
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...",9.07,24,Apr 2011 - Sep 2011
2,3,Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...,9.06,13,Oct 2022 - Dec 2022
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...",9.06,51,Apr 2015 - Mar 2016
4,5,Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...,9.05,10,Apr 2019 - Jul 2019
5,6,"Gintama'TV (51 eps)Apr 2011 - Mar 2012534,105 ...",9.04,51,Apr 2011 - Mar 2012
6,7,Gintama: The FinalMovie (1 eps)Jan 2021 - Jan ...,9.04,1,Jan 2021 - Jan 2021
7,8,Hunter x Hunter TV (148 eps)Oct 2011 - Sep 201...,9.04,148,Oct 2011 - Sep 2014
8,9,Kaguya-sama wa Kokurasetai: Ultra RomanticTV (...,9.04,13,Apr 2022 - Jun 2022
9,10,Gintama': EnchousenTV (13 eps)Oct 2012 - Mar 2...,9.03,13,Oct 2012 - Mar 2013
10,11,Shingeki no Kyojin: The Final Season - Kankets...,9.03,2,Mar 2023 - May 2023
11,12,Ginga Eiyuu DensetsuOVA (110 eps)Jan 1988 - Ma...,9.02,110,Jan 1988 - Mar 1997
12,13,Bleach: Sennen Kessen-hen - Ketsubetsu-tanTV (...,8.99,13,Jul 2023 - Aug 2023
13,14,Fruits Basket: The FinalTV (13 eps)Apr 2021 - ...,8.99,13,Apr 2021 - Jun 2021
14,15,"Gintama.TV (12 eps)Jan 2017 - Mar 2017302,232 ...",8.98,12,Jan 2017 - Mar 2017
15,16,"GintamaTV (201 eps)Apr 2006 - Mar 20101,034,41...",8.94,201,Apr 2006 - Mar 2010
16,17,Koe no KatachiMovie (1 eps)Sep 2016 - Sep 2016...,8.94,1,Sep 2016 - Sep 2016
17,18,3-gatsu no Lion 2nd SeasonTV (22 eps)Oct 2017 ...,8.93,22,Oct 2017 - Mar 2018
18,19,Clannad: After StoryTV (24 eps)Oct 2008 - Mar ...,8.93,24,Oct 2008 - Mar 2009
19,20,Code Geass: Hangyaku no Lelouch R2TV (25 eps)A...,8.91,25,Apr 2008 - Sep 2008
20,21,Gintama Movie 2: Kanketsu-hen - Yorozuya yo Ei...,8.91,1,Jul 2013 - Jul 2013
21,22,Violet Evergarden MovieMovie (1 eps)Sep 2020 -...,8.89,1,Sep 2020 - Sep 2020
22,23,Owarimonogatari 2nd SeasonTV (7 eps)Aug 2017 -...,8.88,7,Aug 2017 - Aug 2017
23,24,Gintama.: Shirogane no Tamashii-hen - Kouhan-s...,8.88,14,Jul 2018 - Oct 2018
24,25,"MonsterTV (74 eps)Apr 2004 - Sep 20051,041,081...",8.87,74,Apr 2004 - Sep 2005
25,26,Kimi no Na wa.Movie (1 eps)Aug 2016 - Aug 2016...,8.84,1,Aug 2016 - Aug 2016
26,27,Kaguya-sama wa Kokurasetai: First Kiss wa Owar...,8.84,1,Dec 2022 - Dec 2022
27,28,Bocchi the Rock!TV (12 eps)Oct 2022 - Dec 2022...,8.83,12,Oct 2022 - Dec 2022
28,29,The First Slam DunkMovie (1 eps)Dec 2022 - Dec...,8.83,1,Dec 2022 - Dec 2022
29,30,Vinland Saga Season 2TV (24 eps)Jan 2023 - Jun...,8.82,24,Jan 2023 - Jun 2023
30,31,Jujutsu Kaisen 2nd SeasonTV (23 eps)Jul 2023 -...,8.82,23,Jul 2023 - Aug 2023
31,32,Gintama.: Shirogane no Tamashii-henTV (12 eps)...,8.81,12,Jan 2018 - Mar 2018
32,33,Kingdom 3rd SeasonTV (26 eps)Apr 2020 - Oct 20...,8.81,26,Apr 2020 - Oct 2021
33,34,Mob Psycho 100 IITV (13 eps)Jan 2019 - Apr 201...,8.80,13,Jan 2019 - Apr 2019
34,35,Shingeki no Kyojin: The Final SeasonTV (16 eps...,8.80,16,Dec 2020 - Mar 2021
35,36,Kimetsu no Yaiba: Yuukaku-henTV (11 eps)Dec 20...,8.79,11,Dec 2021 - Feb 2022
36,37,Kizumonogatari III: Reiketsu-henMovie (1 eps)J...,8.79,1,Jan 2017 - Jan 2017
37,38,"""Oshi no Ko""TV (11 eps)Apr 2023 - Jun 2023645,...",8.79,11,Apr 2023 - Jun 2023
38,39,Haikyuu!! Karasuno Koukou vs. Shiratorizawa Ga...,8.78,10,Oct 2016 - Dec 2016
39,40,Sen to Chihiro no KamikakushiMovie (1 eps)Jul ...,8.78,1,Jul 2001 - Jul 2001
40,41,Monogatari Series: Second SeasonTV (26 eps)Jul...,8.77,26,Jul 2013 - Dec 2013
41,42,Shingeki no Kyojin: The Final Season Part 2TV ...,8.77,12,Jan 2022 - Apr 2022
42,43,Hajime no IppoTV (75 eps)Oct 2000 - Mar 200255...,8.76,75,Oct 2000 - Mar 2002
43,44,"Cowboy BebopTV (26 eps)Apr 1998 - Apr 19991,79...",8.75,26,Apr 1998 - Apr 1999
44,45,Kingdom 4th SeasonTV (26 eps)Apr 2022 - Oct 20...,8.75,26,Apr 2022 - Oct 2022
45,46,"Vinland SagaTV (24 eps)Jul 2019 - Dec 20191,40...",8.74,24,Jul 2019 - Dec 2019
46,47,Mushishi Zoku Shou 2nd SeasonTV (10 eps)Oct 20...,8.73,10,Oct 2014 - Dec 2014
47,48,Shouwa Genroku Rakugo Shinjuu: Sukeroku Futata...,8.72,12,Jan 2017 - Mar 2017
48,49,Mob Psycho 100 IIITV (12 eps)Oct 2022 - Dec 20...,8.71,12,Oct 2022 - Dec 2022
49,50,Rurouni Kenshin: Meiji Kenkaku Romantan - Tsui...,8.71,4,Feb 1999 - Sep 1999

In [247]:
# which anime has highest score
data3[data3['Score'] == data3['Score'].max()]

,Rank,Title,Score,episode,title_time
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.1,64,Apr 2009 - Jul 2010

In [248]:
# give me top 5 anime based on score
data3['Title'].head()

0    Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...
1    Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...
2    Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...
3    Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...
4    Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...
Name: Title, dtype: object

In [249]:
# which anime has highest episode count
data3[data3['episode'] == data3['episode'].max()]

,Rank,Title,Score,episode,title_time
15,16,"GintamaTV (201 eps)Apr 2006 - Mar 20101,034,41...",8.94,201,Apr 2006 - Mar 2010

In [295]:
# QUICK EXAMPLE OF READING A Countries CSV FILE
dat = pd.read_csv(r'pandas_Countries.csv')
data =pd.DataFrame(dat)
data

,country,country_long,currency,capital_city,region,continent,demonym,latitude,longitude,agricultural_land,...,population,women_parliament_seats_pct,rural_population,urban_population,press,democracy_score,democracy_type,median_age,political_leader,title
0,Afghanistan,Islamic State of Afghanistan,Afghan afghani,Kabul,Southern Asia,Asia,Afghan,33.000000,65.000000,383560.0,...,41128771,27.01610,30181937,10946834,2.14,2.97,Authoritarian,12.9,Ashraf Ghani,President
1,Albania,Republic of Albania,Albanian lek,Tirana,Southern Europe,Europe,Albanian,41.000000,20.000000,11655.5,...,2775634,35.71430,1004807,1770827,2.62,5.98,Hybrid regime,33.7,Edi Rama,Prime Minister
2,Algeria,People's Democratic Republic of Algeria,Algerian dinar,Algiers,Northern Africa,Africa,Algerian,28.000000,3.000000,413588.0,...,44903225,8.10811,11328186,33575039,1.71,3.50,Authoritarian,24.0,Abdelmadjid Tebboune,President
3,Andorra,Principality of Andorra,Euro,Andorra la Vella,Southern Europe,Europe,Andorran,42.500000,1.500000,187.2,...,79824,46.42860,9730,70094,3.17,0.00,Unknown,38.9,Xavier Espot Zamora,Head of Government
4,Angola,People's Republic of Angola,Angolan kwanza,Luanda,Middle Africa,Africa,Angolan,-12.500000,18.500000,569525.0,...,35588987,33.63640,11359649,24229338,2.24,3.62,Authoritarian,12.4,João Lourenço,President
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
189,Vietnam,Socialist Republic of Vietnam,Vietnamese dong,Hanoi,South-Eastern Asia,Asia,Vietnamese,16.166667,107.833333,123600.0,...,98186856,30.26050,60123739,38063117,1.04,3.08,Authoritarian,28.4,Nguyễn Phú Trọng,General Secretary of the Communist Party
190,West Bank and Gaza,West Bank and Gaza,Israeli new shekel,Ramallah,Western Asia,Asia,Palestinian,31.900000,35.200000,4449.0,...,5043612,NaN,1145354,3898258,1.75,4.39,Hybrid regime,15.4,NaN,NaN
191,Yemen,Republic of Yemen,Yemeni rial,Sana'a,Western Asia,Asia,Yemeni,15.000000,48.000000,234520.0,...,33696614,0.00000,20491585,13205029,1.27,1.95,Authoritarian,14.8,Abdrabbuh Mansur Hadi,President
192,Zambia,Republic of Zambia,New Zambian kwacha,Lusaka,Eastern Africa,Africa,Zambian,-15.000000,30.000000,238360.0,...,20017675,15.06020,10857387,9160288,2.15,5.61,Hybrid regime,13.2,Edgar Lungu,President
193,Zimbabwe,Republic of Zimbabwe,U.S. dollar,Harare,Eastern Africa,Africa,Zimbabwean,-20.000000,30.000000,162000.0,...,16320537,30.56600,11033499,5287038,1.85,3.16,Authoritarian,14.2,Emmerson Mnangagwa,President

In [296]:
# which countries has highest population
data[data['population'] == data['population'].max()]

,country,country_long,currency,capital_city,region,continent,demonym,latitude,longitude,agricultural_land,...,population,women_parliament_seats_pct,rural_population,urban_population,press,democracy_score,democracy_type,median_age,political_leader,title
75,India,Republic of India,Indian rupee,New Delhi,Southern Asia,Asia,Indian,20.0,77.0,1790450.0,...,1417173173,14.9446,908804812,508368361,1.71,7.23,Flawed democracy,23.9,Narendra Modi,Prime Minister

In [297]:
# what is the capital of the country with highset popuation
data[ data['population']==data['population'].max()]['capital_city']

75    New Delhi
Name: capital_city, dtype: object

In [298]:
# which country has least population
data[data['population'] == data['population'].min()]

,country,country_long,currency,capital_city,region,continent,demonym,latitude,longitude,agricultural_land,...,population,women_parliament_seats_pct,rural_population,urban_population,press,democracy_score,democracy_type,median_age,political_leader,title
179,Tuvalu,Tuvalu,Australian dollar,Funafuti,Polynesia,Oceania,Tuvaluan,-8.0,178.0,18.0,...,11312,6.25,3900,7412,0.0,0.0,Unknown,21.0,Kausea Natano,Prime Minister

In [299]:
# what is the capital of the country with least population
data[ data['population'] == data['population'].min()]['capital_city']

179    Funafuti
Name: capital_city, dtype: object

In [ ]:
# give me top 5 countries with highest democratic score
top5 = data.sort_values(by='democracy_score', ascending=False).head(5)
top5

,country,country_long,currency,capital_city,region,continent,demonym,latitude,longitude,agricultural_land,...,population,women_parliament_seats_pct,rural_population,urban_population,press,democracy_score,democracy_type,median_age,political_leader,title
127,Norway,Kingdom of Norway,Norwegian krone,Oslo,Northern Europe,Europe,Norwegian,62.0,10.0,9859.62,...,5457127,44.9704,891476,4565651,10.00,9.87,Full democracy,35.6,Erna Solberg,Prime Minister
74,Iceland,Republic of Iceland,Iceland krona,Reykjavík,Northern Europe,Europe,Icelander,65.0,-18.0,18720.00,...,381900,47.6190,22945,358955,5.32,9.58,Full democracy,32.1,Katrín Jakobsdóttir,Prime Minister
164,Sweden,Kingdom of Sweden,Swedish krona,Stockholm,Northern Europe,Europe,Swedish,62.0,15.0,30055.40,...,10486941,46.4183,1206837,9280104,9.41,9.39,Full democracy,35.6,Stefan Löfven,Prime Minister
122,New Zealand,New Zealand,New Zealand dollar,Wellington,Australia and New Zealand,Oceania,New Zealander,-41.0,174.0,101540.00,...,5124100,50.4202,672077,4452023,7.27,9.26,Full democracy,32.8,Jacinda Ardern,Prime Minister
46,Denmark,Kingdom of Denmark,Danish krone,Copenhagen,Northern Europe,Europe,Danish,56.0,10.0,26199.90,...,5903037,43.5754,686700,5216337,7.92,9.22,Full democracy,37.2,Mette Frederiksen,Prime Minister

In [328]:
# how many regions are there
data['region'].value_counts().count()

np.int64(22)

In [343]:
#how many countries lie in Eastern Europe region
data[data['region'] == 'Eastern Europe']['country'].count()

np.int64(10)

In [354]:
#who is the political leader of the 2nd highest populated country
data.nlargest(2,'population').iloc[1]['political_leader']

'Xi Jinping'

In [357]:
# how many countries are there whose political leaders are unknown
data[data['political_leader'].isnull()].shape[0]

7

In [365]:
#how many country have Republic in their full name
count = 0
for i in range(len(data)):
    if 'Republic'.lower() in data.iloc[i]['country_long'].lower():
        count += 1       
print(count)

125

In [382]:
#which country in african region has highest population
africa_data=data[(data['continent'] == 'Africa')]
africa_data[africa_data['population'] == africa_data['population'].max()]['country']

125    Nigeria
Name: country, dtype: object